### ISSUE TITLE
keeps crashing 

### ISSUE THREAD

**Issue by usernameeeeeeeeeeeeee** [TelepathicGrunt/WorldBlender-Fabric#4]
crash on world creation

**Comment by TelepathicGrunt** [comment]
Can you please provide your latest.log file after you get the crash to occur? You can find the latest.log file in the logs folder above the mods folder. Post the file here or copy/paste the contents into pastebin.com and give me the link to the paste. Without any info, I cannot do anything which is why I am asking for the log file which will say why it is crashing

**Comment by TelepathicGrunt** [comment]
it's been 6 days and no new info lol. I'll close this report now but I'll reopen it once you can give me your latest.log file
