### ISSUE TITLE
World Blender Portal rendering crashes with Sodium on

### ISSUE THREAD

**Issue by DKLYNTLY** [TelepathicGrunt/WorldBlender-Fabric#9]
[crash-2021-04-26_00.21.52-client.txt](https://github.com/TelepathicGrunt/WorldBlender-Fabric/files/6374273/crash-2021-04-26_00.21.52-client.txt)

**Comment by DKLYNTLY** [comment]
<img width="1280" alt="Screen Shot 2021-04-26 at 12 25 11 AM" src="https://user-images.githubusercontent.com/75499681/116028801-ef140700-a625-11eb-8c0e-b9f2c6eb9dc5.png">

**Comment by DKLYNTLY** [comment]
[crash-2021-04-26_00.24.56-client.txt](https://github.com/TelepathicGrunt/WorldBlender-Fabric/files/6374277/crash-2021-04-26_00.24.56-client.txt)

**Comment by TelepathicGrunt** [comment]
shoot. Why is sodium crashing my portal renderer : concerned :

**Comment by TelepathicGrunt** [comment]
It seems like Sodium 0.1.0 latest official release is not crashing my portal. I noticed you are using 0.1.1-SNAPSHOT sodium. Can you try downgrading sodium and see if it fixes the issue?
![image](https://user-images.githubusercontent.com/40846040/116104406-68d7df00-a67e-11eb-8d32-0615c68ebc3a.png)

**Comment by TelepathicGrunt** [comment]
I just tested with the very latest sodium build from their github and I even threw on sodium extra and I still cannot get the crash to occur. This leaves me thinking this crash is probably caused by a different mod. Or you picked a broken commit from sodium.

Please try using the very latest sodium commit or downgrade to 0.1.0 sodium. If you are still crashing after upgrading/downgrading sodium, we may need to start removing mods to find the problematic mod by making a new world. do ```/setblock ~ ~ ~ world_blender:world_blender_portal```, and keep removing mods (while keeping sodium and world blender on) until the crash goes away? That way we can narrow down which mod it is.

Or if you can send me your modpack or zipped folder of all your mods, I can try narrowing down the conflicting mod myself. But only if you are still crashing with 0.1.0 sodium or latest commit sodium

**Comment by TelepathicGrunt** [comment]
Oof. Since I cannot reproduce the issue and i'm guessing from the lack of response from ruby, this issue has been resolved then or was a one-time thing. Will close now
